version: '3.5'

services:
  db_goods-postgres:
    image: postgis/postgis
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_goods
    volumes:
      - db_goods-db:/var/lib/postgresql/db_goods

  db_goods-redis:
      image: redis
      ports:
      - '6379:6379'
      command: >
        --user user on allcommands allkeys >pass
        restart: unless-stoppe

volumes:
  db_goods-db:


